"""Exports report data as CSV/XLSX/PDF (PROMPT 3 FASE J).

Every exported file is explicitly labeled "RELATÓRIO AUXILIAR" and states,
inside the file itself, that it is NOT an official TSE filing, was never
submitted to any official system, and does not claim to follow the
CONTA+JE layout — this system is not the CONTA+JE and never simulates a
TSE submission (absolute rule of this project's scope). The disclaimer is
baked into the generated bytes, not just a UI label, so it survives the
file being downloaded, forwarded, or opened outside this application.
"""
from __future__ import annotations

import csv
import io
from datetime import date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Font
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

DISCLAIMER = (
    "RELATÓRIO AUXILIAR — uso interno da campanha. Este documento NÃO é uma "
    "prestação de contas oficial ao TSE, não foi enviado a nenhum sistema "
    "oficial e não segue necessariamente o layout exigido pelo CONTA+JE."
)

Column = tuple[str, str]  # (field_key, header_label)


def _generated_at() -> str:
    return datetime.now().strftime("%d/%m/%Y %H:%M")


def _cell_value(value: Any) -> Any:
    """Value as openpyxl/reportlab-friendly Python types — Decimal and
    date/datetime pass through untouched (openpyxl writes both natively,
    preserving the exact figure instead of a float rounding)."""
    if value is None:
        return None
    if isinstance(value, Enum):
        return value.value
    return value


def _text_value(value: Any) -> str:
    """String rendering for CSV/PDF, where every cell is text."""
    if value is None:
        return ""
    if isinstance(value, Enum):
        return str(value.value)
    if isinstance(value, Decimal):
        return f"{value:.2f}"
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    return str(value)


def export_csv(rows: list[dict], *, columns: list[Column], title: str) -> bytes:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow([f"# {title}"])
    writer.writerow([f"# {DISCLAIMER}"])
    writer.writerow([f"# Gerado em {_generated_at()}"])
    writer.writerow([])
    writer.writerow([label for _, label in columns])
    for row in rows:
        writer.writerow([_text_value(row.get(key)) for key, _ in columns])
    # utf-8-sig: Excel needs the BOM to open UTF-8 CSVs with accented text
    # (fornecedor, descrição, ...) without mangling them.
    return buffer.getvalue().encode("utf-8-sig")


def export_xlsx(rows: list[dict], *, columns: list[Column], title: str) -> bytes:
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Relatório"

    sheet.append([title])
    sheet["A1"].font = Font(bold=True, size=14)
    sheet.append([DISCLAIMER])
    sheet["A2"].font = Font(italic=True, size=9, color="B00020")
    sheet.append([f"Gerado em {_generated_at()}"])
    sheet.append([])

    header_row_index = sheet.max_row + 1
    sheet.append([label for _, label in columns])
    for cell in sheet[header_row_index]:
        cell.font = Font(bold=True)

    for row in rows:
        sheet.append([_cell_value(row.get(key)) for key, _ in columns])

    for column_cells in sheet.columns:
        lengths = [len(str(cell.value)) for cell in column_cells if cell.value is not None]
        width = max(lengths, default=10)
        sheet.column_dimensions[column_cells[0].column_letter].width = min(width + 2, 60)

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def export_pdf(rows: list[dict], *, columns: list[Column], title: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5 * cm, bottomMargin=1.5 * cm)
    styles = getSampleStyleSheet()

    elements = [
        Paragraph(title, styles["Title"]),
        Paragraph(DISCLAIMER, styles["Italic"]),
        Paragraph(f"Gerado em {_generated_at()}", styles["Normal"]),
        Spacer(1, 0.5 * cm),
    ]

    table_data = [[label for _, label in columns]]
    for row in rows:
        table_data.append([_text_value(row.get(key)) for key, _ in columns])

    table = Table(table_data, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
            ]
        )
    )
    elements.append(table)
    doc.build(elements)
    return buffer.getvalue()


EXPORTERS = {
    "csv": (export_csv, "text/csv; charset=utf-8", "csv"),
    "xlsx": (export_xlsx, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
    "pdf": (export_pdf, "application/pdf", "pdf"),
}
