"""initial schema

Revision ID: 44bed0a3a5de
Revises: 
Create Date: 2026-09-14 10:57:36.410281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bed0a3a5de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'MANUAL_CORRECTION', 'LINK_DOCUMENT', name='auditaction', native_enum=False, length=30), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compliance_rules',
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legal_source', sa.String(length=255), nullable=True),
    sa.Column('article', sa.String(length=50), nullable=True),
    sa.Column('paragraph', sa.String(length=50), nullable=True),
    sa.Column('inciso', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='ruleseverity', native_enum=False, length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('validation_logic', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compliance_alerts',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', 'HUMAN_REVIEW', name='alerttype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('original_path', sa.String(length=1000), nullable=False),
    sa.Column('processed_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'HUMAN_REVIEW', 'FAILED', 'POSSIBLE_DUPLICATE', name='documentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='ocrconfidence', native_enum=False, length=10), nullable=False),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('extracted_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extracted_supplier_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_razao_social', sa.String(length=255), nullable=True),
    sa.Column('extracted_cnpj', sa.String(length=20), nullable=True),
    sa.Column('extracted_cpf', sa.String(length=20), nullable=True),
    sa.Column('extracted_description', sa.Text(), nullable=True),
    sa.Column('extracted_document_number', sa.String(length=100), nullable=True),
    sa.Column('extracted_payment_method', sa.String(length=100), nullable=True),
    sa.Column('possible_duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['possible_duplicate_of_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_sha256_hash'), 'documents', ['sha256_hash'], unique=False)
    op.create_table('document_items',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_document', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('document_status', sa.Enum('ATTACHED', 'PENDING', 'NOT_REQUIRED', name='documentlinkstatus', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'PENDING_INFORMATION', name='expensestatus', native_enum=False, length=30), nullable=False),
    sa.Column('missing_fields', sa.String(length=500), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('OCR', 'DOCUMENT_PROCESSING', name='processingjobtype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='processingjobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenues',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('donor_document', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('document_status', sa.Enum('ATTACHED', 'PENDING', 'NOT_REQUIRED', name='documentlinkstatus', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('COMPLETE', 'PENDING_INFORMATION', name='revenuestatus', native_enum=False, length=30), nullable=False),
    sa.Column('missing_fields', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('REVENUE', 'EXPENSE', name='transactiontype', native_enum=False, length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('expense_id', sa.String(length=36), nullable=True),
    sa.Column('revenue_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['revenue_id'], ['revenues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('revenues')
    op.drop_table('processing_jobs')
    op.drop_table('expenses')
    op.drop_table('document_items')
    op.drop_index(op.f('ix_documents_sha256_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('compliance_alerts')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('compliance_rules')
    op.drop_table('categories')
    op.drop_table('campaigns')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
