"""storage abstraction: document backup tracking, integration_connections

Revision ID: 99bc4a589590
Revises: b5dcf93d8e46
Create Date: 2026-09-14 12:11:39.816583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bc4a589590'
down_revision: Union[str, None] = 'b5dcf93d8e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('connected_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default on both NOT NULL columns so this never fails against a
    # database that already has document rows (matches each column's
    # Python-side default) — autogenerate leaves NOT NULL columns without a
    # default, which breaks on non-empty tables (same class of bug already
    # hit and fixed in b5dcf93d8e46).
    op.add_column('documents', sa.Column('storage_provider', sa.String(length=30), nullable=False, server_default='local'))
    op.add_column('documents', sa.Column('external_storage_id', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('backup_status', sa.Enum('NOT_CONFIGURED', 'PENDING', 'COMPLETED', 'FAILED', name='backupstatus', native_enum=False, length=20), nullable=False, server_default='NOT_CONFIGURED'))
    op.add_column('documents', sa.Column('backup_storage_provider', sa.String(length=30), nullable=True))
    op.add_column('documents', sa.Column('backup_external_id', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('backup_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('backup_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'backup_error')
    op.drop_column('documents', 'backup_completed_at')
    op.drop_column('documents', 'backup_external_id')
    op.drop_column('documents', 'backup_storage_provider')
    op.drop_column('documents', 'backup_status')
    op.drop_column('documents', 'external_storage_id')
    op.drop_column('documents', 'storage_provider')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
