"""add auth: users role/google/active, sessions, campaign fields

Revision ID: b5dcf93d8e46
Revises: 44bed0a3a5de
Create Date: 2026-09-14 11:56:00.934509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5dcf93d8e46'
down_revision: Union[str, None] = '44bed0a3a5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.add_column('campaigns', sa.Column('candidate_document', sa.String(length=20), nullable=True))
    op.add_column('campaigns', sa.Column('campaign_cnpj', sa.String(length=20), nullable=True))
    op.add_column('campaigns', sa.Column('election_type', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('campaigns', sa.Column('city', sa.String(length=255), nullable=True))
    # server_default so this never fails against a database that already has
    # rows (matches the model's own Python-side default) — autogenerate
    # leaves NOT NULL columns without a default, which breaks on non-empty
    # tables.
    op.add_column('campaigns', sa.Column('status', sa.String(length=30), nullable=False, server_default='ACTIVE'))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # Any pre-existing row would carry the old free-text default ("operator"),
    # which isn't one of the new Role values — normalize before narrowing
    # the column, so the alter_column below never leaves an unreadable row.
    op.execute("UPDATE users SET role = 'VIEWER' WHERE role NOT IN "
               "('ADMIN', 'CAMPAIGN_MANAGER', 'FINANCIAL', 'ACCOUNTANT', 'VIEWER')")

    # SQLite can't ALTER COLUMN TYPE or ADD CONSTRAINT on an existing table
    # directly — batch mode rebuilds the table under the hood, which also
    # works unchanged on PostgreSQL (verified against both, not just
    # inferred: this migration previously only ran cleanly on Postgres via
    # `alter_column`/`create_unique_constraint` directly, and failed with a
    # SQLite syntax error on a fresh `alembic upgrade head` — batch mode
    # fixes that instead of only working "by design").
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Enum('ADMIN', 'CAMPAIGN_MANAGER', 'FINANCIAL', 'ACCOUNTANT', 'VIEWER', name='role', native_enum=False, length=30),
                   existing_nullable=False)
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.alter_column('role',
                   existing_type=sa.Enum('ADMIN', 'CAMPAIGN_MANAGER', 'FINANCIAL', 'ACCOUNTANT', 'VIEWER', name='role', native_enum=False, length=30),
                   type_=sa.VARCHAR(length=50),
                   existing_nullable=False)
    op.drop_column('users', 'active')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'google_id')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'city')
    op.drop_column('campaigns', 'state')
    op.drop_column('campaigns', 'election_type')
    op.drop_column('campaigns', 'campaign_cnpj')
    op.drop_column('campaigns', 'candidate_document')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
