"""gmail suggestions (detection, never auto-import)

Revision ID: c075b2cd186e
Revises: 99bc4a589590
Create Date: 2026-09-14 12:27:05.151296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c075b2cd186e'
down_revision: Union[str, None] = '99bc4a589590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_suggestions',
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=True),
    sa.Column('sender', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachment_id', sa.String(length=200), nullable=False),
    sa.Column('attachment_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IMPORTED', 'REJECTED', name='gmailsuggestionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id', 'attachment_id', name='uq_gmail_suggestion_message_attachment')
    )
    op.create_index(op.f('ix_gmail_suggestions_gmail_message_id'), 'gmail_suggestions', ['gmail_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_suggestions_gmail_message_id'), table_name='gmail_suggestions')
    op.drop_table('gmail_suggestions')
    # ### end Alembic commands ###
